### ISSUE TITLE
LicensePlate module won't install under docker

### ISSUE THREAD

**Issue by brianegge** [codeproject/CodeProject.AI-Server#87]
**Area of Concern**
- [ ] Server
- [X] Behaviour of one or more Modules License Plate Reader
- [X] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**

**Expected behavior**

**Screenshots**

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.2.4-Beta (docker gpu latest)
 - OS: Ubuntu 22.04
 - System RAM 32Gb
 - GPU (if available) GeForce RTX 3080

**Additional context**
```
08:07:42:ALPR: Checking for ROCm support... Done
08:07:42:ALPR: sh: 1: lsmod: not found
08:07:42:ALPR:              Installing CodeProject.AI Analysis Module                
08:07:42:ALPR: ======================================================================
08:07:42:ALPR:                    CodeProject.AI Installer                           
08:07:42:ALPR: ======================================================================
08:07:42:ALPR: 6.07 GiB  available
08:07:42:ALPR: Installing curl...
08:07:42:ALPR: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
08:07:43:ALPR: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.81.0-1ubuntu1.13_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
08:07:43:ALPR: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.81.0-1ubuntu1.13_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
08:07:43:ALPR: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
08:07:43:Module ALPR installed successfully.
08:07:43:
08:07:43:Module 'License Plate Reader' 2.6 (ID: ALPR)
08:07:43:Module Path:   /app/modules/ALPR
08:07:43:AutoStart:     True
08:07:43:Queue:         alpr_queue
08:07:43:Installer exited with code 10
08:07:43:Platforms:     windows,linux,macos,macos-arm64
08:07:43:GPU:           Support disabled
08:07:43:Parallelism:   0
08:07:43:Accelerator:
08:07:43:Half Precis.:  enable
08:07:43:Runtime:       python38
08:07:43:Runtime Loc:   Local
08:07:43:FilePath:      ALPR_adapter.py
08:07:43:Pre installed: False
08:07:43:Start pause:   1 sec
08:07:43:LogVerbosity:
08:07:43:Valid:         True
08:07:43:Environment Variables
08:07:43:AUTO_PLATE_ROTATE            = True
08:07:43:OCR_OPTIMAL_CHARACTER_HEIGHT = 60
08:07:43:OCR_OPTIMAL_CHARACTER_WIDTH  = 36
08:07:43:OCR_OPTIMIZATION             = True
08:07:43:PLATE_CONFIDENCE             = 0.7
08:07:43:PLATE_RESCALE_FACTOR         = 2
08:07:43:PLATE_ROTATE_DEG             = 0
08:07:43:
08:07:43:Error trying to start License Plate Reader (ALPR_adapter.py)
08:07:43:An error occurred trying to start process '/app/modules/ALPR/bin/linux/python38/venv/bin/python3' with working directory '/app/modules/ALPR'. No such file or directory
08:07:43:   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at CodeProject.AI.Server.Modules.ModuleProcessServices.StartProcess(ModuleConfig module)
08:07:43:Module ALPR started successfully.
08:07:43:Please check the CodeProject.AI installation completed successfully
08:07:44:Call to Install on module ALPR has completed.
```

**Comment by xavan83** [comment]
Same for me, do you find a solution?

**Comment by aots74** [comment]
+1 also experiencing this issue

**Comment by yen9912** [comment]
had the same issue. `gpu` tagged images are outdated. gotta use `cuda` now
https://hub.docker.com/layers/codeproject/ai-server/cuda12_2/images/sha256-62a3ea87fae23e4c4651e707671a86a1ab9fa8d7d11a7e88b8d48a6f7a1feca8

docs should be updated

**Comment by xavan83** [comment]
Same issue with docker 2.6.0-cpu and license plate module 3.0.3

**Comment by xavan83** [comment]
Same issue with docker 2.6.1-cpu and  license plate module 3.1.0

**Comment by matthewDDennis** [comment]
Could you please send the contents of the System Info tab
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/8105715/355dd06e-c46a-43db-b3e7-cd48ada6ca95)

**Comment by xavan83** [comment]
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/106675882/51dd2a1b-9dad-4799-a3c3-16eed140073e)

**Comment by xavan83** [comment]
@matthewDDennis any update?

**Comment by matthewDDennis** [comment]
We had some issues with the 2.6.[0,1,2] releases that have been addressed in the 2.6.4 release.
Please give this a try.

**Comment by xavan83** [comment]
The latest docker image available is the 2.6.2

**Comment by xavan83** [comment]
@matthewDDennis @ChrisMaunder any update of the docker images to diagnose this issue?
Thank you

**Comment by xavan83** [comment]
I try the latest docker image published(2.6.5) but still the same issue. 
Here is the logs of the installation:
11:22:44:Preparing to install module 'ALPR'
11:22:44:Downloading module 'ALPR'
11:22:44:Installer script at '/app/setup.sh'
11:22:44:Installing module 'ALPR'
11:22:44:ALPR: Setting verbosity to quiet
11:22:44:ALPR: Hi Docker! We will disable shared python installs for downloaded modules
11:22:44:ALPR: (No schemas means: we can't detect if you're in light or dark mode)
11:22:44:ALPR:              Installing CodeProject.AI Analysis Module                
11:22:44:ALPR: ======================================================================
11:22:44:ALPR:                    CodeProject.AI Installer                           
11:22:44:ALPR: ======================================================================
11:22:44:ALPR: 127.08 GiB of 233.04 GiB available on Docker
11:22:44:ALPR: Installing xz-utils...
11:22:48:ALPR: General CodeProject.AI setup                                          
11:22:48:ALPR: Setting permissions on runtimes folder...done
11:22:48:ALPR: Setting permissions on downloads folder...done
11:22:48:ALPR: Setting permissions on modules download folder...done
11:22:48:ALPR: Creating models download folder...done
11:22:48:ALPR: Setting permissions on models download folder...done
11:22:48:ALPR: Setting permissions on persisted data folder...done
11:22:48:ALPR: GPU support                                                           
11:22:48:ALPR: CUDA (NVIDIA) Present: No
11:22:54:ALPR: ROCm (AMD) Present:    (attempt to install rocminfo... ) No
11:22:54:ALPR: MPS (Apple) Present:   No
11:22:55:ALPR: Reading module settings.......done
11:22:55:ALPR: Processing module ALPR 3.1.0                                          
11:22:55:ALPR: Installing Python 3.8
11:22:55:ALPR: Python 3.8 is already installed
11:23:05:ALPR: Ensuring PIP in base python install...  done
11:23:08:ALPR: Upgrading PIP in base python install... done
11:23:08:ALPR: Virtual Environment already present
11:23:08:ALPR: Checking for Python 3.8...(Found Python 3.8.19) All good
11:23:11:ALPR: Upgrading PIP in virtual environment... done
11:23:14:Response timeout. Try increasing the timeout value
11:23:17:ALPR: Installing updated setuptools in venv... done
11:23:17:ALPR: deb http://security.ubuntu.com/ubuntu focal-security main
11:23:30:ALPR: Searching for libssl1.1...installing...   done
11:23:30:ALPR: Ensuring symlinks are created...Done
11:23:32:ALPR: Downloading OCR models...Expanding... done.
11:23:32:ALPR: Moving contents of ocr-en-pp_ocrv4-paddle.zip to paddleocr...done.
11:23:32:ALPR: Installing Python packages for License Plate Reader
11:23:32:ALPR: Installing GPU-enabled libraries: No
11:23:35:ALPR: Searching for python3-pip...All good.
11:23:39:ALPR: Ensuring PIP compatibility... done
11:23:39:ALPR: Python packages will be specified by requirements.linux.txt
11:23:41:ALPR:   - Installing PaddelPaddle, the Deep Learning platform...Already installed
11:23:43:ALPR:   - Installing PaddleOCR, the OCR toolkit based on PaddlePaddle...Already installed
11:23:45:ALPR:   - Installing imutils, the image utilities library...Already installed
11:23:47:ALPR:   - Installing Pillow, a Python Image Library...Already installed
11:23:49:ALPR:   - Installing OpenCV, the Computer Vision library for Python...Already installed
11:23:51:ALPR:   - Installing NumPy, a package for scientific computing...Already installed
11:23:51:ALPR: Installing Python packages for the CodeProject.AI Server SDK
11:23:54:ALPR: Searching for python3-pip...All good.
11:23:59:ALPR: Ensuring PIP compatibility... done
11:23:59:ALPR: Python packages will be specified by requirements.txt
11:24:01:ALPR:   - Installing Pillow, a Python Image Library...Already installed
11:24:03:ALPR:   - Installing Charset normalizer...Already installed
11:24:04:ALPR:   - Installing aiohttp, the Async IO HTTP library...Already installed
11:24:06:ALPR:   - Installing aiofiles, the Async IO Files library...Already installed
11:24:08:ALPR:   - Installing py-cpuinfo to allow us to query CPU info...Already installed
11:24:10:ALPR:   - Installing Requests, the HTTP library...Already installed
11:24:10:ALPR: Scanning modulesettings for downloadable models...No models specified
11:24:10:ALPR: Executing post-install script for License Plate Reader
11:24:10:ALPR: Applying PaddleOCR patch
11:24:27:ALPR: /app/setup.sh: line 328:  2489 Illegal instruction     (core dumped) "$venvPythonCmdPath" "$moduleStartFilePath" --selftest > /dev/null
11:24:27:ALPR: Self test: Self-test failed
11:24:27:ALPR: Module setup time 00:01:33
11:24:27:ALPR:                 Setup complete                                        
11:24:27:ALPR: Total setup time 00:01:43
11:24:27:Module ALPR installed successfully.
11:24:27:Installer exited with code 0
11:24:27:Running module using: /app/modules/ALPR/bin/linux/python38/venv/bin/python3
11:24:27:
11:24:27:Attempting to start ALPR with /app/modules/ALPR/bin/linux/python38/venv/bin/python3 "/app/modules/ALPR/ALPR_adapter.py"
11:24:27:
11:24:27:Module 'License Plate Reader' 3.1.0 (ID: ALPR)
11:24:27:Valid:            True
11:24:27:Module Path:      <root>/modules/ALPR
11:24:27:Starting /app...es/ALPR/bin/linux/python38/venv/bin/python3 "/app/modules/ALPR/ALPR_adapter.py"
11:24:27:Module Location:  Internal
11:24:27:AutoStart:        True
11:24:27:Queue:            alpr_queue
11:24:27:Runtime:          python3.8
11:24:27:Runtime Location: Local
11:24:27:FilePath:         ALPR_adapter.py
11:24:27:Start pause:      3 sec
11:24:27:Parallelism:      0
11:24:27:LogVerbosity:
11:24:27:Platforms:        all
11:24:27:GPU Libraries:    not installed
11:24:27:GPU:              do not use
11:24:27:Accelerator:
11:24:27:Half Precision:   enable
11:24:27:Environment Variables
11:24:27:AUTO_PLATE_ROTATE            = True
11:24:27:CROPPED_PLATE_DIR            = <root>/Server/wwwroot
11:24:27:MIN_COMPUTE_CAPABILITY       = 6
11:24:27:MIN_CUDNN_VERSION            = 7
11:24:27:OCR_OPTIMAL_CHARACTER_HEIGHT = 60
11:24:27:OCR_OPTIMAL_CHARACTER_WIDTH  = 30
11:24:27:OCR_OPTIMIZATION             = True
11:24:27:PLATE_CONFIDENCE             = 0.7
11:24:27:PLATE_RESCALE_FACTOR         = 2
11:24:27:PLATE_ROTATE_DEG             = 0
11:24:27:REMOVE_SPACES                = False
11:24:27:ROOT_PATH                    = <root>
11:24:27:SAVE_CROPPED_PLATE           = False
11:24:27:
11:24:27:Started License Plate Reader module
11:24:30:Module ALPR started successfully.
11:24:48:Module ALPR has shutdown
11:24:48:ALPR_adapter.py: has exited

**Comment by xavan83** [comment]
> I have the same issue, did you manage to solve it?

No still the same problem

**Comment by JaysonWallis** [comment]
Thanks xavan83 - I have just wasted a full day trying to make this work before finding your post.  I will watch here for a solution.

**Comment by xavan83** [comment]
@matthewDDennis @ChrisMaunder anything we can do to help you solve this issue?
Upgrade to  Ubuntu 24.04 and still the same issue

**Comment by magic7s** [comment]
Same issue. If I jump into the container (as root), I get this. Not sure if thats the issue or not. 

2.6.5 / 3.2.2

```
root@4a419de0218d:/app/modules/ALPR# python3 ALPR_adapter.py
Traceback (most recent call last):
  File "/app/modules/ALPR/ALPR_adapter.py", line 5, in <module>
    from codeproject_ai_sdk import RequestData, ModuleRunner, JSON
ModuleNotFoundError: No module named 'codeproject_ai_sdk'
```

**Comment by xavan83** [comment]
> Same issue. If I jump into the container (as root), I get this. Not sure if thats the issue or not.
> 
> 2.6.5 / 3.2.2
> 
> ```
> root@4a419de0218d:/app/modules/ALPR# python3 ALPR_adapter.py
> Traceback (most recent call last):
>   File "/app/modules/ALPR/ALPR_adapter.py", line 5, in <module>
>     from codeproject_ai_sdk import RequestData, ModuleRunner, JSON
> ModuleNotFoundError: No module named 'codeproject_ai_sdk'
> ```

I also try that without better result

**Comment by Daschmi** [comment]
Same hier

**Comment by xavan83** [comment]
I try with server 2.8.0 and the message is a little bit different:

10:01:33:ALPR_adapter.py:   File "/app/modules/ALPR/ALPR_adapter.py", line 11, in 
10:01:33:ALPR_adapter.py:     from ALPR import init_detect_platenumber, detect_platenumber
10:01:33:ALPR_adapter.py:   File "/app/modules/ALPR/ALPR.py", line 7, in 
10:01:33:ALPR_adapter.py:     import utils.tools as tool
10:01:33:ALPR_adapter.py: ModuleNotFoundError: No module named 'utils.tools'
